### ISSUE TITLE
caching database queries

### ISSUE THREAD

**Issue by beyazit** [kamp-us/monorepo#186]
### Describe the feature you would like to see added

I recommend caching database queries so that the 'pano' can respond faster to higher request in the future.

### Describe the solution you'd like

We use prisma as ORM. For the caching layer, a Redis powered [prisma middleware](https://www.prisma.io/docs/concepts/components/prisma-client/middleware) can be written.

**Comment by usirin** [comment]
Thank you for the request, but at this point, it's too early for us to introduce a caching layer. The target audience is only the kampus users, which is currently ~650 people. If everybody signs up and uses the site to generate load around approximately 1RPS (request per second), this means 650RPS. 

We should be just fine with not having a cache atm. If anything we can increase the size of the RDS instance once we have load problems. Caching should always be the last resort as it creates data sync problems easily. Thank you for the suggestion though, we can def get back to this when we start to see load problems caused by db requests.
