### ISSUE TITLE
refactor: add spacing to buttons for comment edit

### ISSUE THREAD

**Issue by cansirin** [kamp-us/monorepo#334]
This is a preview of editing a comment. There must be spacing between `Kaydet` and `Iptal` as well as between comment text area.

![Image](https://user-images.githubusercontent.com/8138047/226154496-f47ab93a-24b6-4b4d-b9be-7945d9b90ad5.png)

**Comment by mertsabinov** [comment]
Hi, 
I'm not sure if we don't really need a space between the buttons and the text area. The reason is that when I looked at it in three different browsers, there was a space between the buttons and the textarea.

Safari:
![Screenshot 2023-03-19 at 10 35 01 AM](https://user-images.githubusercontent.com/88425310/226160708-56b74e25-3299-44b9-a1a1-f70976be4a59.png)


Brave: 
![Screenshot 2023-03-19 at 10 35 35 AM](https://user-images.githubusercontent.com/88425310/226160730-7755b0f8-1b45-4e6c-8301-7faddf50e652.png)

Google Chorme: 
![Screenshot 2023-03-19 at 10 37 21 AM](https://user-images.githubusercontent.com/88425310/226160811-16c08df2-8dad-4ed0-9df7-b5c637667383.png)

**Comment by cansirin** [comment]
> Hi, I'm not sure if we don't really need a space between the buttons and the text area. The reason is that when I looked at it in three different browsers, there was a space between the buttons and the textarea.
> 
> Safari: ![Screenshot 2023-03-19 at 10 35 01 AM](https://user-images.githubusercontent.com/88425310/226160708-56b74e25-3299-44b9-a1a1-f70976be4a59.png)
> 
> Brave: ![Screenshot 2023-03-19 at 10 35 35 AM](https://user-images.githubusercontent.com/88425310/226160730-7755b0f8-1b45-4e6c-8301-7faddf50e652.png)
> 
> Google Chorme: ![Screenshot 2023-03-19 at 10 37 21 AM](https://user-images.githubusercontent.com/88425310/226160811-16c08df2-8dad-4ed0-9df7-b5c637667383.png)

Thank you so much for this detailed analysis. My screenshot was from Firefox browser. Unfortunately this doesn't work on Firefox :(

**Comment by mertsabinov** [comment]
thank you for the info i will work on it
